name: dns-scout
version: '6.8'
summary: DNS Scout for Linux/MacOS
description: |
  DNS Scout for Linux/MacOS pulls and displays DNS records in a color-coded console output.
  It stands out by filtering out non-essential information, presenting users with a cleaner,
  more focused view of the DNS data.

grade: stable
confinement: strict
type: app

base: core22
architectures:
  - amd64 
  - arm64
  - armhf
  - i386
build-snaps:
  - go
parts:
  dns-scout:
    plugin: go
    source-type: git
    source: https://github.com/careyjames/dns-scout
apps:
  dns-scout:
    command: bin/dns-scout
    plugs: 
      - network
      - network-bind
      - home
      - removable-media
