# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, kalilinux/kali-rolling]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.2'

    - name: Build
      run: cd src && go build -v -o ../bin/dns-scout main.go && cd -

    - name: Test
      run: cd src && go test -v ./... && cd -

    - name: Security Scan
      run: gosec ./...

    - name: Deploy (if on main branch)
      if: github.ref == 'refs/heads/main'
      run: ./deploy.sh # Replace with your actual deployment script
