# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [kalilinux/kali-rolling, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os == 'kalilinux/kali-rolling' && 'self-hosted' || matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Debug - Show current directory
      run: pwd

    - name: Debug - List directory contents
      run: ls -al

    - name: install dependencies
      run: go mod tidy  

    - name: Build
      run: go build -v -o ./bin/dns-scout main.go

    - name: Test
      run: go test -v ./...